from glob import glob

src_files = glob( 'src/*.c' )
include_files = glob( 'src/*.h' )

SharedLibrary( 'foobar', src_files )

Package( projectname = 'libfoobar',
         version     = '1.2.3',
         type        = [ 'zip', 'targz' ],
         source      = src_files + include_files + [ 'SConstruct' ] )
